
version: "3"
# 服务列表，命令：docker run
services:
  # 服务名称，任意，不重复即可
  redis:
    # 指定服务名称，命令：--name redis
    # 如果不指定，则将默认用docker-compose.yml所在文件夹名_服务名称_n命名
    container_name: redisNet
    # 指定镜像：命令 redis:latest
    image: redis:latest
    # 指定端口：命令 -p 主机端口:容器端口
    ports:
      - "6379:6379"
    # 数据容器卷
    #volumes:
      # /root/docker/compose/redis/redis.conf:/etc/redis/redis.conf
      # /root/docker/compose/redis/data:/data
    # 加入指定网络，容器间必须要处于同一个网络才能通过容器名称进行调用
    networks:
      - mynet
    # 运行命令
    # command: redis-server /etc/redis/redis.conf  


  mysql:
    container_name: mysqlNet
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
        # 等同于 -e MYSQL_ROOT_PASSWORD指定root的登录密码
      MYSQL_ROOT_PASSWORD: '123456'  
    volumes:
      - /docker/mysql/data:/var/lib/mysql
      # 这里的my.cnf可以从原来的安装的MySQL里面找，如果没有不配置也不影响，只是为了方便外部更改
      - /docker/mysql/conf:/etc/mysql/conf.d 
      - /docker/mysql/logs:/var/log/mysql 
    networks:
      # 注意加入同一个网络
      - mynet


    # 解决外部无法访问
    command: --default-authentication-plugin=mysql_native_password
networks:
  mynet:
